### ISSUE TITLE
TODO for Rebase

### ISSUE THREAD

**Issue by jminardi** [Voxel8/Marlin#7]
* [x] ADC/Laser distance sensor

* [x] Configuration File changes

* [x] Add 'ok' at end of ConfigurationStore.cpp

* [x] Configuration_adv.h changes

* [x] Pneumatics

* [x] Home Y before X when home all is sent

* [x] Allow Z tool offset

* [x] Pause Command M399

**Comment by jminardi** [comment]
All changes we need to make can be seen at this diff:

https://github.com/MarlinFirmware/Marlin/compare/Integration...Voxel8:v8_gen3_devel
